### ISSUE TITLE
letter-recog.py in samples/python2 doesn't work for opencv 3.0.0

### ISSUE THREAD

**Issue by psdh** [Itseez/opencv#6568]
I tried running the python2 sample for random forest creation in `samples/python2/letter_recog.py`

- OpenCV version: 3.0.0
- Host OS: Linux (Ubuntu 16.04)

### Expected behaviour
The example should create the random forest model, predict and return an accuracy score.

### Actual behaviour
```
loading data ../data/letter-recognition.data ...
Traceback (most recent call last):
  File "samples/python2/letter_recog.py", line 161, in <module>
    model = Model()
  File "samples/python2/letter_recog.py", line 61, in __init__
    self.model = cv2.RTrees()
AttributeError: 'module' object has no attribute 'RTrees'
```

This is expected, since the python bindings expect, `cv2.ml.RTree_create()` instead of `cv2.RTrees()`

**Comment by alalek** [comment]
[Fixed](https://github.com/Itseez/opencv/commit/4ed2d6328bf1f418ef83fe0e8fb821c921b10ba2#diff-15ac67dcc88a2c7c948bae3f6012a5e4R64) in master

**Comment by psdh** [comment]
Hi! @alalek 
Thanks for the quick response. I had tried to make the same changes that you committed, but it still fails for me.
I get a `TypeError: ml_StatModel.train() takes at most 3 arguments (5 given)` on train function for the `RTrees` model

**Comment by alalek** [comment]
Use ".__doc__" method's field (it is string) to see function's parameters description.
Try to get help on Q/A site: http://answers.opencv.org , here we track bugs and feature requests only.
